config/routes.rb
Rails.application.routes.draw do
  resources :formula_tintas
  resources :base_tintas
  resources :tintas
  resources :mallas
  resources :lineas_uv
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root :to => 'turnos#index'
end

app/models/base_tinta.rb
class BaseTinta < ApplicationRecord
    has_many :formula_tintas , inverse_of: :base_tinta, dependent: :destroy
    accepts_nested_attributes_for :formula_tintas, reject_if: :all_blank, allow_destroy: true
end

app/controllers/base_tintas_controller.rb
class BaseTintasController < ApplicationController
  before_action :set_base_tinta, only: [:show, :edit, :update, :destroy]

  # GET /base_tintas
  # GET /base_tintas.json
  def index
    @base_tintas = BaseTinta.all
  end

  # GET /base_tintas/1
  # GET /base_tintas/1.json
  def show
  end

  # GET /base_tintas/new
  def new
    @base_tinta = BaseTinta.new
    @base_tinta.formula_tintas.build
  end

  # GET /base_tintas/1/edit
  def edit
  end

  # POST /base_tintas
  # POST /base_tintas.json
  def create
    @base_tinta = BaseTinta.new(base_tinta_params)

    respond_to do |format|
      if @base_tinta.save
        format.html { redirect_to @base_tinta, notice: 'Base tinta was successfully created.' }
        format.json { render :show, status: :created, location: @base_tinta }
      else
        format.html { render :new }
        format.json { render json: @base_tinta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_tintas/1
  # PATCH/PUT /base_tintas/1.json
  def update
    respond_to do |format|
      if @base_tinta.update(base_tinta_params)
        format.html { redirect_to @base_tinta, notice: 'Base tinta was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_tinta }
      else
        format.html { render :edit }
        format.json { render json: @base_tinta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_tintas/1
  # DELETE /base_tintas/1.json
  def destroy
    @base_tinta.destroy
    respond_to do |format|
      format.html { redirect_to base_tintas_url, notice: 'Base tinta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_tinta
      @base_tinta = BaseTinta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_tinta_params
      params.require(:base_tinta).permit(:cod, :descripcion_base,
      formula_tintas_attributes:[:id, :base_tinta_id, :descripcion, :cantidad])
    end
end

app/helpers/base_tintas_helper.rb
module BaseTintasHelper
end

app/views/base_tintas/_form.html.erb
<%= simple_form_for(@base_tinta) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :cod %>
    <%= f.input :descripcion_base %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/base_tintas/edit.html.erb
<h1>Editing Base Tinta</h1>

<%= render 'form', base_tinta: @base_tinta %>

<%= link_to 'Show', @base_tinta %> |
<%= link_to 'Back', base_tintas_path %>

app/views/base_tintas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Base Tintas</h1>

<table>
  <thead>
    <tr>
      <th>Cod</th>
      <th>Descripcion base</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_tintas.each do |base_tinta| %>
      <tr>
        <td><%= base_tinta.cod %></td>
        <td><%= base_tinta.descripcion_base %></td>
        <td><button class="waves-effect waves-light btn boton_ver"><%= link_to 'Show', base_tinta ,class:'boton '%></button></td>
        <td><button class="waves-effect waves-light btn boton_editar" ><%= link_to 'Edit', edit_base_tinta_path(base_tinta),class:'boton ' %></button></td>
        <td><button class="waves-effect waves-light btn boton_eliminar"><%= link_to 'Destroy', base_tinta, method: :delete, data: { confirm: 'Are you sure?' },class:'boton ' %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base Tinta', new_base_tinta_path %>

app/views/base_tintas/new.html.erb
<h1>New Base Tinta</h1>

<%= render 'form', base_tinta: @base_tinta %>

<%= link_to 'Back', base_tintas_path %>

app/views/base_tintas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cod:</strong>
  <%= @base_tinta.cod %>
</p>

<p>
  <strong>Descripcion base:</strong>
  <%= @base_tinta.descripcion_base %>
</p>

<%= link_to 'Edit', edit_base_tinta_path(@base_tinta) %> |
<%= link_to 'Back', base_tintas_path %>