config/routes.rb
Rails.application.routes.draw do
  resources :formula_tintas
  resources :base_tintas
  resources :tintas
  resources :mallas
  resources :lineas_uv
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root :to => 'turnos#index'
end

app/models/formula_tinta.rb
class FormulaTinta < ApplicationRecord
  
  belongs_to :tinta
  belongs_to :base_tinta
  
end

app/controllers/formula_tintas_controller.rb
class FormulaTintasController < ApplicationController
  before_action :set_formula_tinta, only: [:show, :edit, :update, :destroy]

  # GET /formula_tintas
  # GET /formula_tintas.json
  def index
    @formula_tintas = FormulaTinta.all
    @formula_tintas = FormulaTinta.all
    
  end

  # GET /formula_tintas/1
  # GET /formula_tintas/1.json
  def show
  end

  # GET /formula_tintas/new
  def new
    @formula_tinta = FormulaTinta.new
    @base_tinta = BaseTinta.all
    @formula_tintas = FormulaTinta.all
  end

  # GET /formula_tintas/1/edit
  def edit
  end

  # POST /formula_tintas
  # POST /formula_tintas.json
  def create
    @formula_tinta = FormulaTinta.new(formula_tinta_params)

    respond_to do |format|
      if @formula_tinta.save
        format.html { redirect_to @formula_tinta, notice: 'Formula tinta was successfully created.' }
        format.json { render :show, status: :created, location: @formula_tinta }
      else
        format.html { render :new }
        format.json { render json: @formula_tinta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formula_tintas/1
  # PATCH/PUT /formula_tintas/1.json
  def update
    respond_to do |format|
      if @formula_tinta.update(formula_tinta_params)
        format.html { redirect_to @formula_tinta, notice: 'Formula tinta was successfully updated.' }
        format.json { render :show, status: :ok, location: @formula_tinta }
      else
        format.html { render :edit }
        format.json { render json: @formula_tinta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formula_tintas/1
  # DELETE /formula_tintas/1.json
  def destroy
    @formula_tinta.destroy
    respond_to do |format|
      format.html { redirect_to formula_tintas_url, notice: 'Formula tinta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formula_tinta
      @formula_tinta = FormulaTinta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formula_tinta_params
      params.require(:formula_tinta).permit(:tinta_id, :tinta_base_id, :cantidad,
      base_tintas_attributes:[:cod, :descripcion_base])
    end
end

app/helpers/formula_tintas_helper.rb
module FormulaTintasHelper
end

app/views/formula_tintas/_form.html.erb
<%= simple_form_for(@formula_tinta) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= 
       f.association :tinta,
       collection: Tinta.all, 
       label_method: :pantone, 
       value_method: :id, 
       as: :select, 
       include_blank: 'Seleccione Tinta'
    %>
    <%=
       f.association :base_tinta,
       collection: BaseTinta.all, 
       label_method: :descripcion_base, 
       value_method: :id, 
       as: :select, 
       include_blank: 'Seleccione Base'
    %>
    <%= 
      f.input :cantidad 
    %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/formula_tintas/edit.html.erb
<h1>Editing Formula Tinta</h1>

<%= render 'form', formula_tinta: @formula_tinta %>

<%= link_to 'Show', @formula_tinta %> |
<%= link_to 'Back', formula_tintas_path %>

app/views/formula_tintas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formula Tintas</h1>

<table>
  <thead>
    <tr>
      <th>Tinta</th>
      <th>Base tinta</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formula_tintas.each do |formula_tinta| %>
      <tr>
        <td><%= formula_tinta.tinta.cod %></td>
        <td><%= formula_tinta.base_tinta.descripcion_base %></td>
        <td><%= formula_tinta.cantidad %></td>
        <td><%= link_to 'Show', formula_tinta %></td>
        <td><%= link_to 'Edit', edit_formula_tinta_path(formula_tinta) %></td>
        <td><%= link_to 'Destroy', formula_tinta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formula Tinta', new_formula_tinta_path %>

app/views/formula_tintas/new.html.erb
<h1>New Formula Tinta</h1>

<%= render 'form', formula_tinta: @formula_tinta %>

<%= link_to 'Back', formula_tintas_path %>

app/views/formula_tintas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tinta:</strong>
  <%= @formula_tinta.tinta %>
</p>

<p>
  <strong>Base tinta:</strong>
  <%= @formula_tinta.base_tinta %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @formula_tinta.cantidad %>
</p>

<%= link_to 'Edit', edit_formula_tinta_path(@formula_tinta) %> |
<%= link_to 'Back', formula_tintas_path %>