config/routes.rb
Rails.application.routes.draw do
  resources :formula_tintas
  resources :base_tintas
  resources :tintas
  resources :mallas
  resources :lineas_uv
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root :to => 'turnos#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intercalco</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <!--/Navbar-->
    <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%=link_to "Lineas De Tintas", lineas_uv_path%></li>
        <li><%=link_to "Mallas", mallas_path%></li>
        <li><%=link_to "Tintas", tintas_path%></li>
        <li><%=link_to "Productos", productos_path%></li>
        <li><%=link_to "Formula Tintas", formula_tintas_path%></li>
        <li><%=link_to "Base Para Tintas", base_tintas_path%></li>
      </ul>
    </div>
  </nav>
  <!--/Navbar-->
  
    <div class="container">
      <%= yield %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.js"></script>
    </div>

    
  </body>
</html>